apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-simulator
  template:
    metadata:
      labels:
        app: node-simulator
    spec:
      containers:
      - name: simulator
        image: cloudnetmonitor/simulator:latest
        env:
        - name: BACKEND_URL
          value: "http://backend:3001"
        - name: NUM_NODES
          value: "4"
        - name: UPDATE_INTERVAL
          value: "1000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m" 